# Generated by Django 5.0 on 2025-10-03 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='petitionvote',
            unique_together=set(),
        ),
    ]
