# Generated by Django 5.0 on 2025-10-03 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_alter_petitionvote_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviepetition',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='moviepetition',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='petitionvote',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='petitionvote',
            name='user',
        ),
    ]
